### ISSUE TITLE
psd2html命令行使用报错

### ISSUE THREAD

**Issue by byself** [purplebamboo/psd2html#1]
我的ruby安装在D:\soft\Ruby\；你的项目克隆在D:\project\git\psd2html。

在D:\project\git\psd2html这个目录下运行cmd并输入命令：

> psd2html ./example/simple.psd ./test.html

报错内容：
D:/soft/Ruby/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- nokogiri/2.2/nokogiri (LoadError)

请教这是什么原因，该怎没解决？是psd2html命令对文件路径有什么要求吗？绝对地址？

**Comment by fiultyy** [comment]
遇到同样的问题~

**Comment by zhangshupi88** [comment]
运行遇到同样的问题，请问怎么解决，当前目录下运行psd2html ./example/simple.psd ./text.html  
 报错：/Library/Ruby/Gems/2.3.0/gems/psd2html-0.0.6/lib/psd2html/psconvertor/textLink.rb:3:in `<module:PsConvertor>': uninitialized constant Psd2html::PsConvertor::Text (NameError)
